title: BlackPhants
subtitle: BlackPhants의 기술블로그입니다.
description: >-
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is
  optimized for speed and readability.
url: 'https://blackphants.github.io'
baseurl: ''
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Contact
    url: /contact
author_logo: profile.png
author: BlackPhants
author_bio: 안녕하세요. BlackPhants의 기술블로그입니다. 저희는 게임을 제작 중 입니다.
author_email: 
author_location: Korea
author_website_url: ''
typewrite-text: 으아아아아아아아아아아아아아아아아악!!!! 살ㄹ려줏...
hero_cover_img: sample_cover.jpg
author_work_experiences:
  - company_name: Google
    company_logo: google.png
    company_url: 'https://google.com'
    designation: Software Engineer
    description: Worked on various Google Products
    visibility: true
  - company_name: Microsoft
    company_logo: microsoft.png
    company_url: 'https://microsoft.com'
    designation: Azure Developer
    description: Worked on various Azure Cloud Products
    visibility: true
author_education_details:
  - college_logo: mit.png
    college_name: MIT
    college_url: 'https://mit.org'
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: true
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: true
twitter_username: 
github_username: 
facebook_username: 
linkedin_username: 
behance_username: 
instagram_username: 
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 
mailchimp_form_url: >-
  https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0
formspree_email: johndoe@gmail.com
olvy_organization: devlopr
olvy_widget_type: sidebar
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: 'false'
show_author_education_details: 'false'
show_author_project_details: 'false'
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  products:
    output: true
  authors:
    output: true
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
jekyll_admin:
  homepage: posts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
